trigger:
- master

pool:
  name: default
  vmImage: node1
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  inputs:
        containerRegistry: 'dockerhubconnection'
        repository: '9673483686 / azuredevops'
        command: 'buildAndPush'
        Dockerfile: '**/AzureDockerfile'
        tags: 'latest'
